### ISSUE TITLE
Improve Welcome Message in all Surveys

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-survey#14]
"We should think about how to phrase the welcome messages at the beginning of all survey. It should be clear how the data are used etc."

_Originally posted by @lnnrtwttkhn in https://github.com/lnnrtwttkhn/version-control-survey/issues/13#issuecomment-1750255695_

**Comment by lnnrtwttkhn** [comment]
The recording and evaluation of your responses are handled anonymously in the research group "Mechanisms of Learning & Change" at the University of Hamburg.
    This means that a personal password is used (see below), which you create based on a rule, and which no one else knows except you.
    
    I agree with the described handling of the collected data.
    The recording and evaluation of data are carried out anonymously in the research group "Mechanisms of Learning & Change" at the University of Hamburg-
    meaning by using a personal password that I created myself following a rule, and which no one else knows except me.
    
    I am aware that I can revoke my consent for the storage or retention of my data without any disadvantages to me.
    I have been informed that I can request the deletion of all my data at any time, but only by using my personal password.
    If I do not know my password, my anonymized data is not subject to the right of withdrawal according to Article 7 of the General Data Protection Regulation (GDPR).
    I consent to my anonymized data being used for educational purposes

**Comment by lnnrtwttkhn** [comment]
hi @konradpa, I added a note about data usage in [0e206fe](https://github.com/lnnrtwttkhn/version-control-survey/commit/0e206fedb9780c4fa03bfc6d404c25220593ec15).

- [x] could you please add this note to all surveys? thanks!

**Comment by lnnrtwttkhn** [comment]
hi @konradpa, I updated the welcome message once again in [ba5a022](https://github.com/lnnrtwttkhn/version-control-survey/commit/ba5a022825a161a800bb5ec8258bddfbf44dd9d5). could you align all the other surveys? thanks!

**Comment by lnnrtwttkhn** [comment]
@konradpa, I think this can be closed, right?

**Comment by lnnrtwttkhn** [comment]
this seems done. closing.
