### ISSUE TITLE
add questions to introduction to git survey

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-survey#15]
hey @konradpa, could you add these questions to the introduction survey (different from the pre-course survey that we send out in advance, do we have a survey for this yet?). basically, questions that accompany the ["intro to version control" chapter](https://lennartwittkuhn.com/version-control-book/chapters/intro-version-control.html). the questions are currently [here](https://lennartwittkuhn.com/version-control-book/chapters/intro-version-control.html#exercises) and pasted below.

could you please

- [x] optional: create a new survey with questions about the "intro to version control"
- [x] add the questions to the survey (maybe you can also display the "solutions" after participants entered their responses.
- [x] remove the questions from the version control book.

thanks!

---

Imagine a scenario where you crafted a brilliant paragraph for your paper, but then accidentally ruined it. How would you retrieve the earlier brilliant version? Is it even possible?

Solution:

The possibility of retrieving the brilliant version exists only when you have made a copy of the previous paper version. The risk of losing valuable versions frequently results in “implicit” version control, where multiple versions of the same file are saved. This approach, however, is error-prone and can lead to additional confusion and frustration.

Consider a situation where you are working with five co-authors on a paper. How do you handle the changes and comments they make to the document? If you’re using LibreOffice Writer or Microsoft Word and you accept changes made using the “Track Changes” option, what happens to the history of those modifications?

Solution:

Collaborative writing using traditional word processors presents challenges. Collaborators either need to work on the document sequentially, which slows down the writing process, or you have to send versions to each collaborator and manually merge their comments into the document. While the “track changes” option can highlight modifications and simplify merging, accepting changes erases their history, making it impossible to identify who suggested the change, the reason behind it, or when it was incorporated into the document. Even online word processors like Google Docs or Microsoft Office Online do not entirely resolve these issues.

**Comment by lnnrtwttkhn** [comment]
this was fixed with #16, right @konradpa? could you check and if yes, close this issue? thanks!

**Comment by konradpa** [comment]
Yes, this is closed with #16
