### ISSUE TITLE
Pre- course questionnaire

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-survey#4]
### pre-course questionnaire:
operating system
"which field of work / research are you most interested in?" (psychology (clincal, education, therapy, ..), cog neuro
which degree / career step " (e.g., phd, clinical work, etc.)
previous  experience
"what do you think version control is?"
"what do you think this course is about?" don't copy-paste the title.
if experience with git: "is there something specific you'd like to learn about git?"
are you familiar with programming (any language)
motivation
"what do you hope to learn?"
"do you have any worries / fears regarding the course?"
remember to add codeword 
 [Orginal issue](https://github.com/lnnrtwttkhn/version-control-course-uhh-ws23/issues/14#issue-1887300513)

**Comment by lnnrtwttkhn** [comment]
- [x] fix formatting of "please specify choice" - make consistent across instances (low priority)
- [x] increase text field size, if possible
- [x] add codeword
- [ ] add generic introduction text, e.g.,

> welcome to this survey! this survey is part of the course "version control". your responses are only used to

> I will share aggregated results of the numeric items afterwards. All answers are anonymous and they are meant to form a basis for frank discussions about addressing issues. Free text items will not be shared with everyone and provide space to communicate only with me (I might share clearly innocuous examples of free text items). Please flag sharing issues in your free text response, if applicable. 
> Please be 100% honest, in particular about issues that you find pressing and very difficult to discuss in another format.    


> This is an anonymous survey to capture candid feedback on the climate, organization, and science in a scientific laboratory. It is meant to be distributed to all members of the lab, including permanent staff, students, postdocs, interns, summer students, and technicians. Not all questions will apply to all participants. The goal is to identify issues in the lab that the lab head can work with members to address to improve lab culture. 

Anonymity and data usage
> All answers are anonymous and will be aggregated to form a basis for frank discussions about addressing issues.
> Free text items will not be shared with everyone and prove a space to communicate only with xxx. Only innocuous examples of free text items will be shared. Please flag sharing issues in your free text response, if applicable. 
> Please be as honest as possible, in particular about issues that you find pressing and very difficult to discuss in another format.

**Comment by konradpa** [comment]
added by #12 and #9
